---
title: "2021 List of Homework"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
## week 2
github <- list(
  title = "GitHub",
  topics = c("Creating a new project"),
  pdf = "",
  rmd = "homework/week_01/hw_01_github_remotes.Rmd",
  html = "homework/week_01/hw_01_github_remotes.html",
  data = "homework/week_01/palmer_penguins.csv",
  key = ""
)

## week 3
forking_workflows <- list(
  title = "Forking workflows",
  topics = c("Forking workflows"),
  pdf = "",
  rmd = "homework/week_02/hw_02_forking_workflow.Rmd",
  html = "homework/week_02/hw_02_forking_workflow.html",
  data = "",
  key = ""
)

## week 4
getting_help <- list(
  title = "Getting help",
  topics = c("Getting help"),
  pdf = "",
  rmd = "homework/week_03/hw_03_getting_help.Rmd",
  html = "homework/week_03/hw_03_getting_help.html",
  data = "",
  key = "homework/week_03/hw_03_getting_help_key.html"
)

## week 5
databases <- list(
  title = "Databases",
  topics = c("Relational databases"),
  pdf = "",
  rmd = "homework/week_04/hw_04_databases.Rmd",
  html = "homework/week_04/hw_04_databases.html",
  data = "",
  key = ""
)

## week 6
data_viz <- list(
  title = "Data visualization",
  topics = c("Data visualization"),
  pdf = "",
  rmd = "homework/week_05/hw_05_visualization.Rmd",
  html = "homework/week_05/hw_05_visualization.html",
  data = "homework/week_05/data/siscowet.csv",
  key = ""
)

## week 7
publishing <- list(
  title = "Publishing with R Markdown",
  topics = c("Publishing with R Markdown"),
  pdf = "",
  rmd = "homework/week_06/hw_06_publishing.Rmd",
  html = "homework/week_06/hw_06_publishing.html",
  data = "homework/week_06/hw_06_template.Rmd",
  key = "homework/week_06/hw_06_publishing_key.html"
)

## week 8
presentations <- list(
  title = "Markdown presentations",
  topics = c("Markdown presentations"),
  pdf = "",
  rmd = "homework/week_08/hw_08_presentations.Rmd",
  html = "homework/week_08/hw_08_presentations.html",
  data = "",
  key = ""
)

## week 9
packages <- list(
  title = "R packages",
  topics = c("R packages"),
  pdf = "",
  rmd = "homework/week_07/hw_07_packages.Rmd",
  html = "homework/week_07/hw_07_packages.html",
  data = "",
  key = ""
)
```

