---
title: "2024 List of Topics"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## session 1 ####
lec_1 <- list(
  title = "Introduction & background concepts",
  topics = c("Introduction & background concepts"),
  pdf = c(""),
  rmd = "",
  html = "lectures/day_01/lec_01_intro-concepts.html",
  background = c("[Chap 1 & 2, Cowperwait & Metcalf (2009)](references/Introductory_Time_Series_With_R.pdf)",
                 "[Chap 6, Hyndman & Athanasopoulos (2018)](https://otexts.org/fpp2/decomposition.html)",
                 "[Chap 3, Holmes et al (2021)](https://atsa-es.github.io/atsa-labs/chap-ts.html)"),
  zoom = ""
)

## session 2 ####
lab_1 <- list(
  title = "Basic ts functions",
  topics = c("Basic ts functions"),
  pdf = c(""),
  rmd = "",
  html = "lectures/day_01/lab_01_basic_ts_funcs.html",
  background = c("<br><br>"),
  zoom = ""
)

## session 3 ####
lec_2 <- list(
  title = "Autoregressive & random-walk models",
  topics = c("Autoregressive & random-walk models"),
  pdf = c(""),
  rmd = "",
  html = "lectures/day_01/lec_02_autoregressive-models.html",
  background = c("[Chap 4, Cowperwait & Metcalf (2009)](references/Introductory_Time_Series_With_R.pdf)",
                 "[Chap 3, Holmes et al (2021)](https://atsa-es.github.io/atsa-labs/chap-ts.html)<br>"),
  zoom = ""
)

## session 4 ####
lab_2 <- list(
  title = "Simulating & fitting models",
  topics = c("Simulating & fitting models"),
  pdf = c(""),
  rmd = "",
  html = "lectures/day_01/lab_02_sim-fit.html",
  background = c("<br><br>"),
  zoom = ""
)

## session 5 ####
lab_3 <- list(
  title = "Installing software & packages",
  topics = c("Installing software & packages"),
  pdf = c(""),
  rmd = "",
  html = "lectures/day_01/lab_03_install-software.html",
  background = c("<br><br>"),
  zoom = ""
)

## session 6 ####
lec_3 <- list(
  title = "Univariate state-space models",
  topics = c("Univariate state-space models"),
  pdf = c(""),
  rmd = "",
  html = "lectures/day_02/lec_03_univariate-SSM.html",
  background = c("[Chap 12, Cowperwait & Metcalf (2009)](references/Introductory_Time_Series_With_R.pdf)",
                 "[Auger-Méthé et al (2021)](references/Auger‐Methe_guide_state-space_models.pdf)",
                 "<br>"),
  zoom = ""
)

## session 7 ####
lab_4 <- list(
  title = "Fitting state-space models",
  topics = c("Fitting state-space models"),
  pdf = c(""),
  rmd = "",
  html = "lectures/day_02/lab_04_fitting-ssm.html",
  background = c("<br><br>"),
  zoom = ""
)

## session 8 ####
lec_4 <- list(
  title = "Multivariate state-space models",
  topics = c("Multivariate state-space models"),
  pdf = c(""),
  rmd = "",
  html = "lectures/day_02/lec_04_multivariate-SSM.html",
  background = c("[Matrix math review](https://atsa-es.github.io/atsa-labs/chap-basicmat.html)",
                 "<br>"),
  zoom = ""
)

## session 9 ####
lab_5 <- list(
  title = "Analyzing animal movement",
  topics = c("Analyzing animal movement"),
  pdf = c(""),
  rmd = "",
  html = "lectures/day_02/lab_05_animal-movement.html",
  background = c("[Jonsen et al (2003)](references/Jonsen_2003_animal_movement.pdf)","<br>"),
  zoom = ""
)

## session 10 ####
lab_6 <- list(
  title = "Estimating species interactions",
  topics = c("Estimating species interactions"),
  pdf = c(""),
  rmd = "",
  html = "lectures/day_02/lab_06_species-interactions.html",
  background = c("[Ives et al (2003)](references/Ives_2003_MAR_models.pdf)",
                 "[Hampton et al (2013)](references/Hampton_2013_MAR_review.pdf)",
                 "<br>"),
  zoom = ""
)

## session 11 ####
lec_5 <- list(
  title = "Dynamic Factor Analysis",
  topics = c("Dynamic Factor Analysis"),
  pdf = c(""),
  rmd = "",
  html = "lectures/day_03/lec_05_intro-to-DFA.html",
  background = c("[Zuur et al (2003)](references/Zuur_2003_DFA.pdf)",
                 "<br><br>"),
  zoom = ""
)

## session 12 ####
lab_7 <- list(
  title = "Identifying common trends",
  topics = c("Identifying common trends"),
  pdf = c(""),
  rmd = "",
  html = "lectures/day_03/lab_07_intro-to-DFA.html",
  background = c("<br><br>"),
  zoom = ""
)

## session 13 ####
lec_6 <- list(
  title = "Dynamic Linear Models",
  topics = c("Dynamic Linear Models"),
  pdf = c(""),
  rmd = "",
  html = "lectures/day_03/lec_06_intro-to-DLMs.html",
  background = c("<br><br>"),
  zoom = ""
)

## session 14 ####
lab_8 <- list(
  title = "Forecasting",
  topics = c("Forecasting"),
  pdf = c(""),
  rmd = "",
  html = "lectures/day_03/lab_08_forecasting.html",
  background = c("<br><br>"),
  zoom = ""
)

## session 15 ####
lab_9 <- list(
  title = "Review",
  topics = c("Review"),
  pdf = c(""),
  rmd = "",
  html = "",
  background = c("<br><br>"),
  zoom = ""
)
```



