---
title: "Schedule & course materials"
output: html_document
---

<br>

#### Navigating through a slide deck

* Use the arrow keys (&#8592;/&#8594;) on your keyboard to go forward or backward

* Press the "o" key on any slide to show you an overview of the slide deck

* In overview mode, click on a slide or press "esc" to zoom in on it

* You can also print the slides to a pdf by selecting the "print" option from your browser's File menu.


```{r child = "_timeline.Rmd", include=FALSE}
```

```{r child = "_list_of_lectures.Rmd", include=FALSE}
```

```{r week_lecs, include = FALSE}
## empty list for lecs
week_lecs <- vector("list", 30)
names(week_lecs) <- paste0("L", seq(30))
## lecture topics
## week 1: Jan 4-6
week_lecs$L1 <- intro_1
week_lecs$L2 <- intro_2
week_lecs$L3 <- analysis_steps
## week 2: Jan 9-13
week_lecs$L4 <- organization_styles
week_lecs$L5 <- github
week_lecs$L6 <- version_control
## week 3: Jan 16-20
week_lecs$L7 <- holiday_1
week_lecs$L8 <- remotes
week_lecs$L9 <- workflows
## week 4: Jan 23-27
week_lecs$L10 <- working_with_data
week_lecs$L11 <- data_ingest
week_lecs$L12 <- getting_help
## week 5: Jan 30 - Feb 3
week_lecs$L13 <- databases_1
week_lecs$L14 <- databases_2
week_lecs$L15 <- databases_3
## week 6: Feb 6-10
week_lecs$L16 <- metadata
week_lecs$L17 <- analysis_visualization
week_lecs$L18 <- markdown_1
## week 7: Feb 13-17
week_lecs$L19 <- markdown_2
week_lecs$L20 <- markdown_3
week_lecs$L21 <- markdown_4
## week 8: Feb 20-24
week_lecs$L22 <- holiday_2
week_lecs$L23 <- packages_1
week_lecs$L24 <- packages_2
## week 9: Feb 27 - Mar 3
week_lecs$L25 <- shiny_1
week_lecs$L26 <- shiny_2
week_lecs$L27 <- guest_holmes
## week 10: Mar 6-10
week_lecs$L28 <- code_reviews
week_lecs$L29 <- ethics
week_lecs$L30 <- docker
```

```{r topics, include = FALSE, eval = FALSE}
lec_titles <- lapply(week_lecs, function(x) { if(is.list(x)) {x$title} else {""} })
## topics formatted for html
lec_titles_html <- sapply(lapply(lec_titles, paste, "<br>", collapse = ""), c)
names(lec_titles_html) <- NULL
```

```{r lecture_topics, include = FALSE}
lec_topics <- lapply(week_lecs, function(x) { if(is.list(x)) {x$topics} else {""} })
## topics formatted for html
lec_topics_html <- sapply(lapply(lec_topics, paste, "<br>", collapse = ""), c)
names(lec_topics_html) <- NULL
```

```{r lec_links, include = FALSE}
## HTML
slide_links <- lapply(week_lecs, function(x) { if(is.list(x)) {c(x$html)} else {""} })
slide_links_html <- sapply(lapply(slide_links, function(x) {
  if(length(x)>1) {
    tmp1 <- paste0("[",
                   as.character(fontawesome::fa("file-alt", height = "2em", fill = "#3399f3")),
                   " (", 1:length(x), ")](")
    } else {
      tmp1 <- paste0("[",
                     as.character(fontawesome::fa("file-alt", height = "2em", fill = "#3399f3")),
                     "](")
      }
  tmp2 <- ")"
  tmp <- paste0(tmp1, x, tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse = "<br>")
  tmp}), c)

## Rmd
source_links <- lapply(week_lecs, function(x) { if(is.list(x)) {c(x$rmd)} else {""} })
source_links_html <- sapply(lapply(source_links, function(x) {
  if(length(x)>1) {
    tmp1 <- paste0("[",
                   as.character(fontawesome::fa("file-code", height = "2em", fill = "#3399f3")),
                   " (", 1:length(x), ")](")
    } else {
      tmp1 <- paste0("[",
                     as.character(fontawesome::fa("file-code", height = "2em", fill = "#3399f3")),
                     "](")
      }
  tmp2 <- ")"
  tmp <- paste0(tmp1,x,tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse = "<br>")
  tmp}), c)

## PDF
pdf_links <- lapply(week_lecs, function(x) { if(is.list(x)) {c(x$pdf)} else {""} })
pdf_links_html <- sapply(lapply(pdf_links, function(x) {
  if(length(x)>1) {
    tmp1 <- paste0("[",
                   as.character(fontawesome::fa("file-pdf", height = "2em", fill = "#3399f3")),
                   " (", 1:length(x), ")](")
    } else {
      tmp1 <- paste0("[",
                     as.character(fontawesome::fa("file-pdf", height = "2em", fill = "#3399f3")),
                     "](")
      }
  tmp2 <- ")"
  tmp <- paste0(tmp1, x, tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse = "<br>")
  tmp}), c)
```

```{r zoom_links, include = FALSE}
zoom_links <- lapply(week_lecs, function(x) { if(is.list(x)) {x$zoom} else {""} })
## topics formatted for html
zoom_links_html <- sapply(lapply(zoom_links, function(x) {
  if(length(x)>1) {
    tmp1 <- paste0("[",
                   as.character(fontawesome::fa("file-video", height = "2em", fill = "#3399f3")),
                   " (", 1:length(x), ")](")
    } else {
      tmp1 <- paste0("[",
                     as.character(fontawesome::fa("file-video", height = "2em", fill = "#3399f3")),
                     "](")
      }
  tmp2 <- ")"
  tmp <- paste0(tmp1, x, tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse = "<br>")
  tmp}), c)
```

```{r youtube_links, include = FALSE, eval = FALSE}
youtube_links <- lapply(week_lecs, function(x) { if(is.list(x)) {x$youtube} else {""} })
## topics formatted for html
youtube_links_html <- sapply(lapply(youtube_links, function(x) {
  tmp1 <- "[YouTube]("; tmp2 <- ")"
  tmp <- paste0(tmp1, x, tmp2)
  tmp[x==""] <- ""
  tmp <- paste(tmp, collapse = "<br>")
  tmp}), c)
names(youtube_links_html) <- NULL
```

```{r background_links, include = FALSE}
background_links <- lapply(week_lecs, function(x) { if(is.list(x)) {x$background} else {""} })
## topics formatted for html
background_links_html <- sapply(lapply(background_links, paste, "<br>", collapse = ""), c)
names(background_links_html) <- NULL
```

```{r generate_table, echo=FALSE}
## data frame with dates & topics
syl_txt <- data.frame(
  date = qtr,
  lec_topics = lec_topics_html,
  lec_links = slide_links_html,
  # rmd_links = source_links_html,
  # pdf_links = pdf_links_html,
  # zoom_links = zoom_links_html,
  # youtube_links = youtube_links_html,
  background_links = background_links_html
)
colnames(syl_txt) <- c("Date", "Topics",
                       "Notes", # "Source (Rmd)", "Slides (pdf)",
                       # "Zoom recording",
                       "Background")
rownames(syl_txt) <- NULL

## generate table
kableExtra::kable(syl_txt, format = "html", caption = " ",
                  align = "clcc", escape = FALSE) %>%
  kable_styling(bootstrap_options = "striped",
                full_width = FALSE,
                position = "left") %>%
  column_spec(c(1,3), width = "6em") %>%
  column_spec(4, width = "15em") %>%
  scroll_box(height = "700px", extra_css = "border-style: none;")
```

