---
title: "Reference materials"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

**Students are not required to purchase any materials for the course, as we will rely upon freely available software and information sources**.

<br>

### Books & vignettes with specific `R` examples

* Holmes, E. E., M. D. Scheuerell, and E. J. Ward. *Applied Time Series Analysis for Fisheries and Environmental data*. [eBook available here](https://atsa-es.github.io/atsa-labs/)

* Holmes EE, Ward EJ, Scheuerell MD. 2014. *Analysis of Multivariate Time Series Using the MARSS Package*. [pdf available here](https://cran.r-project.org/web/packages/MARSS/vignettes/UserGuide.pdf)

* Hyndman RJ, Athanasopoulos G. 2018. *Forecasting: Principles and Practice*. [eBook available here](https://otexts.org/fpp2/)

<br>

### Some classic textbooks that you may find helpful

* Box GEP, Jenkins GM, Reinsel GC. 2008. *Time Series Analysis: Forecasting and Control*. John Wiley & Sons, Hoboken, New Jersey.

* Brockwell PJ, Davis RA. 2010. *Introduction to Time Series and Forecasting*. Springer, New York.

* Durbin J, Koopman SJ. 2012. *Time Series Analysis by State Space Methods*. Oxford University Press, Oxford.

* Harvey AC. 1991. *Forecasting, Structural Time Series Models and the Kalman Filter*. Cambridge University Press, Cambridge.

* Petris G, Petrone S, Campaginoli P. 2009. *Dynamic Linear Models with R*. Springer, New York.

* Pole A, West M, Harrison J. 1994. *Applied Bayesian Forecasting and Time Series Analysis*. Chapman & Hall/CRC, Boca Raton, Florida. 

* Shumway DH, Stoffer DS. 2006. *Time Series Analysis and Its Applications: With R Examples*. Springer, New York. [R scripts and data here](https://github.com/nickpoison/tsa4)

* West M, Harrison J. 1997. *Bayesian Forecasting and Dynamic Models*. Springer, New York.

<br>

### Examples of papers using MARSS models

* Elmstrom EJ, Holtgrieve GW, Scheuerell MD, Schauer AJ, Leazer K. 2024. Climate and landform interact to control the source and transport of nitrate in Pacific Northwest rivers. Communications Earth & Environment 5:90 (Available [here](./references/Elmstrom_2024_climate_controls.pdf))

* Jankowski K, Houser JN, Scheuerell MD, Smits AP. 2021. Warmer winters increase phytoplankton biomass in a large floodplain river. Journal of Geophysical Research: Biogeosciences 126:e2020JG006135 (Available [here](./references/Jankowski_2021_Mississippi_chla.pdf))

* Quinn TP, Scheuerell MD, Losee JP, Hanada D. 2022. Multidecadal trends in body size of Puget Sound Chinook salmon: Analysis of data from the Tengu Derby, a culturally unique fishery. Marine and Coastal Fisheries 14:e10205 (Available [here](./references/Quinn_2022_tengu_derby.pdf))

<br>

### Using GitHub

* [Creating a GitHub account](./references/github_signup.html)

* [Creating a GitHub Personal Access Token](./references/github_pat_creation.html)

* [Intro to GitHub](https://fish549.github.io/website/lectures/week_02/lec_04_intro_github.html)


