---
title: "Syllabus"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

<br>

# Course overview

This course is intended to give students an overview of the theory and practical aspects of fitting time series models to fisheries and environmental data. The course will cover topics ranging from autocorrelation and crosscorrelation, autoregressive (AR) and moving average (MA) models, univariate and multivariate state-space models, and estimating model parameters. This course also covers various aspects of assessing model performance and evaluating model diagnostics. The course is focused almost exclusively on problems and analyses in the time domain, and only briefly addresses methods for the frequency domain. In general, students will focus on conceptualizing analyses, implementing analyses, and making inference from the results.


<br>

# Learning objectives

By the end of the course, students should be able to:

* Understand the elements to classical decomposition

* Understand how to use ACF and PACF to identify orders of ARMA(*p*,*q*) models for time series data

* Apply appropriate diagnostic measures to identify any shortcomings in model assumptions

* Understand how to use information theoretic methods and cross validation for model selection

* Understand how to combine state and observation models into a state-space model

* Use multivariate time series models with covariates to identify influential explanatory variables and do perturbation analyses

* Use Dynamic Factor Analysis to identify common patterns among many time series

* Use Dynamic Linear Models to allow for changing relationships between a response variable and any explanatory variable(s)

* Prepare forecasts with uncertainty using time series models

<br>

# Instructor

[**Dr. Mark Scheuerell**](https://fish.uw.edu/faculty/mark-scheuerell/)  
Assistant Unit Leader, Washington Cooperative Fish and Wildlife Research Unit  
Associate Professor, School of Aquatic & Fishery Sciences  
[scheuerl@uw.edu](mailto:scheuerl@uw.edu)

<br>

# Meeting times & locations

W/Th/F from 8:30-5:00

<br>

# Pre-requisites

Students should have a working knowledge of the [**R**](https://www.r-project.org/) computing software, such as that provided in FISH 552/553.

<br>

# Classroom conduct

I am dedicated to providing a welcoming and supportive learning environment for all students, regardless of their background, identity, physical appearance, or manner of communication. Any form of language or behavior used to exclude, intimidate, or cause discomfort will not be tolerated. In order to foster a positive and professional learning environment, I ask the following:

* Please let me know if you have a name or set of preferred pronouns that you would like me to use

* Please let me know if *anyone* in class says something that makes you feel uncomfortable<sup>[[1](#endnotes)]</sup>

In addition, I encourage the following kinds of behaviors:

* Use welcoming and inclusive language

* Show courtesy and respect towards others

* Acknowledge different viewpoints and experiences

* Gracefully accept constructive criticism

Although I strive to create and use inclusive materials in this course, there may be overt or covert biases in the course material due to the lens with which it was written. Your suggestions about how to improve the value of diversity in this course are encouraged and appreciated.  

**Please note**: If you believe you have been a victim of an alleged violation of the [Student Conduct Code](https://www.washington.edu/admin/rules/policies/WAC/478-121TOC.html) or you are aware of an alleged violation of the [Student Conduct Code](https://www.washington.edu/admin/rules/policies/WAC/478-121TOC.html), you have the right to [report it to the University](https://www.washington.edu/cssc/for-students-2/).

<br>

# Technology

This course will revolve around hands-on computing exercises that demonstrate the topics of interest. Therefore, students are strongly recommended to bring their own laptop to class, although students are certainly free to work with one another. **For students without access to a personal laptop**: it is possible to check out UW laptops for an entire quarter (see the [Student Services office](https://education.uw.edu/admissions/office-of-student-services) for details).

All of the software we will be using is free and platform independent, meaning students may use macOS, Linux, or Windows operating systems. In addition to a web browser, we will be using the free [**R**](https://www.r-project.org/) software and the desktop version of the [**R Studio**](https://www.rstudio.com/products/rstudio-desktop/) integrated development environment (IDE). We will also be using various packages not contained in the base installation of **R**, but we will wait and install them at the necessary time. The instructor will be available during the first week of class to help students troubleshoot any software installation problems.

We will be using [**Git**](https://git-scm.com/downloads), a free and open source version control system for tracking changes to our files. 

We will be using [**PostgreSQL**](https://www.postgresql.org/download/) to create and access relational databases.

Students will also be required to have a user account on [**GitHub**](https://github.com/), which we will be using for file hosting and communications via "issues". If you do not already have an account, you can sign up for a free one [here](https://github.com/join?source=header-home). The instructor will provide training on how to use the intended features in **GitHub**.

<br>

# Teaching methodology

This course will introduce new material primarily through prepared slides and hands-on demonstrations. Students will be expected to work both individually and collaboratively (to the extent possible given the current conditions); course content and evaluation will emphasize the communication of ideas and the ability to think critically more so than a specific pathway or method. Other areas of this website provide an overview of the topics to be covered, including links to weekly reading assignments, lecture materials, computer labs, and homework assignments.

<br>

# Communication

This course will involve a *lot* of communication between and among students and the instructor. Short questions should be addressed to me via email; I will try my best to respond to your message within 24 hours. Under more normal circumstances, detailed questions would be addressed to me in person--either after class or during a scheduled meeting. In this case, however, we will schedule one-on-one or group Zoom calls as needed.

In addition to email and Zoom, we will use the "Issues" feature in **GitHub** to ask questions and assist others. Specifically, questions and answers can be posted to the issues in the course's "assistance" repository [here](https://github.com/FISH497/assistance/issues).

<br>

# Evaluation

Students will be evaluated on their knowledge of course content and their ability to communicate their understanding of the material via individual homework assignments (80%) and their active participation in class (20%). There will be 8 homework assignments, each counting toward 10% of the final grade. Please note, **all assignments must be turned in to achieve a passing grade**.

### Homework

Homework will be assigned each Friday of weeks 2-9 and will be due by 11:59 PM 9 days later on the following Sunday (weeks 3-10). The instructor will evaluate and return student homework assignments within one week of their due date. **If for some reason you cannot meet the homework deadline, contact the instructor as soon as possible to discuss other options**. Please see the [Homework](homework.html) page for more details.

### Participation

Data science is about communicating your ideas and findings to others. As such, this course will require students to engage with the instructor and one another in small groups. I expect all students to contribute to our discussions of concepts, results, bugs/errors, etc. 

Students should discuss any potential schedule conflicts with the instructor during the first week of class.

<br>

## Endnotes

[1] If the instructor should be the one to say something that makes a student uncomfortable, the student should feel free to contact the Director of the School of the Environment.


